### ISSUE TITLE
Какие требования к Windows?

### ISSUE THREAD

**Issue by BigTolly** [andrewmat2000/youtube-dpi-free#1]
На Windows 7 64bit при установке программы получаю сообщение:
This program requires Windows Service Pack 1 or later.

**Comment by andrewmat2000** [comment]
Удалось выполнить запуск на виртуальной машине. Ждите новый релиз. Создам отдельный архив под Windows 7. Установочник сделать не получиться. Но надеюсь, что не будет проблем с тем чтобы создать папку и ярлык.
![image](https://github.com/user-attachments/assets/e448825b-be1c-4d10-a1df-85e25d7e53ac)

**Comment by andrewmat2000** [comment]
Релиз выпущен, можно проверять.
https://github.com/andrewmat2000/youtube-dpi-free/releases/tag/v.1.1
