### ISSUE TITLE
Пожелание

### ISSUE THREAD

**Issue by iHastr** [andrewmat2000/youtube-dpi-free#2]
Добавьте возможность запоминать размер окна и его расположение на экране. При каждом запуске сбрасывается на размер по умолчанию в центре экрана. Спасибо!

**Comment by andrewmat2000** [comment]
Сегодня/завтра выпущу новый релиз с этой возможностью, ожидайте )

**Comment by andrewmat2000** [comment]
Релиз выпущен, можно проверять.
https://github.com/andrewmat2000/youtube-dpi-free/releases/tag/v.1.1
